name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    timeout-minutes: 10
    runs-on: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install uv and package
        run: |
          python -m pip install --quiet uv
          uv pip install --quiet --system -e .[build]
      - name: Build
        run: |
          python -m build
      - name: Create installer
        run: |
          pyinstaller eyelink_track.spec
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name:  eyelink_track--${{ github.sha }}
          path: |
            dist/eyelink_track.exe